# Generated by Django 4.1.7 on 2023-04-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0002_rename_product_productattribute_related_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='related_product',
            new_name='product',
        ),
    ]
