# Generated by Django 4.1.7 on 2023-04-11 16:11

import attributes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=attributes.models.DecimalFields(decimal_places=2, max_digits=8),
        ),
    ]
