# Generated by Django 4.1.7 on 2023-04-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0008_alter_product_price'),
    ]

    operations = [
    ]
